language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
- bundle exec rails db:schema:dump
deploy:
  provider: heroku
  api_key:
    secure: W1i54HD6XCCezbAjyLYpZnvnOjWg3zLLQqyU6X5VPEYlPbcjc0PvwWGHJBCPUQWsBhlM+FzQT2o7AHdJnj3rx7FPoaR/Qfx1FYFTXUUke/s0O5cbANQ9nPy2yQ1Gz5bUoYrIyYPppM4FwWTiKCF7S/lwsoHWItNfJ50ujYxCZ6g1uFpIZeCJ44lzuN/zgoV1qnuTczoYBqu2Uj6rMu0z39z9gav4Q5QSWiyOxI8Ei3BtVZDexpdiNF4EDzZqG8Iu0HYaGIA7c5xmKIBCpvZxS7YXs3VNvKV9M0X0yBeobc6pZw53Scpv4gGKWYPua1XckA9LKGmjdKzSkJbnxRuPapAMI8CIUq7IlQrNVWfzJVup05VuU797NKBuMbRK4LfpNpN9lag2vU6+vWP/RDUaFO2uElp9ocYtFpIqDXU+y6H1bXnxw80VIp4iJ02U2W3kAmH7gLkfM5crlosksTa58vIP1wNy3/3gIYXbB0iorz6t1hlV7LWwOyl0dutqY8EZIlvzdeMk2bxYXjwN9fulAsTZPIhlZEn9I9VcoBzfCCcJWRfgiJRtVe0ufjqvBrFrZRdDxrBCBLzyh6fz7eUO//iBuD7yF4GMUF4BIDwASsQ8SPHrkDZgKJxD6kRsZ7Hemrvlbk0m8Y4gXaxHzYfFOmKPNsGQxs+eqE8ZjqJxwso=
  app: rails-engine-denver
  skip_cleanup: true
  on:
    branch: main
  run: rails db:schema:dump
